/* NexOS — kernel/pkg/pkg_store.h
 * Compile-time embedded package store.
 * pkg_store.c is auto-generated by:  make packages
 * MIT License */
#pragma once
#include <stdint.h>

typedef struct {
    const char    *name;      /* e.g. "hello.npkg"             */
    const uint8_t *data;      /* pointer to embedded byte array */
    uint32_t       size;      /* byte count                     */
} npkg_store_entry_t;

/* Null-terminated array; last entry has name == NULL. */
extern const npkg_store_entry_t npkg_store[];
